### ISSUE TITLE
Angular SSR

### ISSUE THREAD

**Issue by SanderElias** [wynfred/ngx-masonry#63]
In Angular SSR, I'm getting the following error:
```error
ERROR TypeError: Cannot read property 'appended' of undefined
    at NgxMasonryComponent.itemLoaded (/home/sander/Documents/temp/universalTest/dist/universalTest/server/vendors~home-home-module.js:1:4056)
    at NgxMasonryComponent.add (/home/sander/Documents/temp/universalTest/dist/universalTest/server/vendors~home-home-module.js:1:3926)
    at Timeout.<anonymous> (/home/sander/Documents/temp/universalTest/dist/universalTest/server/vendors~home-home-module.js:1:6934)
    at ZoneDelegate.invokeTask (/home/sander/Documents/temp/universalTest/dist/universalTest/server/main.js:1:711094)
    at Object.onInvokeTask (/home/sander/Documents/temp/universalTest/dist/universalTest/server/main.js:1:1155828)
    at ZoneDelegate.invokeTask (/home/sander/Documents/temp/universalTest/dist/universalTest/server/main.js:1:710984)
    at Zone.runTask (/home/sander/Documents/temp/universalTest/dist/universalTest/server/main.js:1:703659)
    at ZoneTask.invokeTask (/home/sander/Documents/temp/universalTest/dist/universalTest/server/main.js:1:712679)
    at Timeout.ZoneTask.options.useG.invoke (/home/sander/Documents/temp/universalTest/dist/universalTest/server/main.js:1:712508)
    at Timeout.timer [as _onTimeout] (/home/sander/Documents/temp/universalTest/dist/universalTest/server/main.js:1:750470)
ERROR TypeError: Cannot read property 'appended' of undefined
```

This is because of this code in the component:
```typescript
  private itemLoaded(item: NgxMasonryDirective) {
    // Tell Masonry that a child element has been added
    if (item.prepend) {
      this.masonryInstance.prepended(item.element.nativeElement);
    } else {
      this.masonryInstance.appended(item.element.nativeElement);
    }
```
In SSR the ` this.masonryInstance` is _not_ set. There is more code that needs to be wrapped into the `isPlatform`

**Comment by SanderElias** [comment]
If you like I can do an PR that will fix all SSR issues?

**Comment by wynfred** [comment]
PR is always welcome!

**Comment by Cafnio** [comment]
Created a PR about this issue.

**Comment by wynfred** [comment]
Thank you for the PR!
