### ISSUE TITLE
SSR: ngOnDestroy generate "Cannot read property 'remove' of undefined"

### ISSUE THREAD

**Issue by Egaro555** [wynfred/ngx-masonry#83]
When SSR retrun page with massonry components the server fail when components was destroyed
```
TypeError: Cannot read property 'remove' of undefined
    at NgxMasonryComponent.remove (/app/dist/frontoffice/server/vendors~src-app-xxx-module.js:3661:49)
    at NgxMasonryDirective.ngOnDestroy (/app/dist/frontoffice/server/vendors~src-app-xxx-module.js:3857:21)
    at executeOnDestroys (/app/dist/frontoffice/server/main.js:81930:18)
    at cleanUpView (/app/dist/frontoffice/server/main.js:81833:5)
    at destroyViewTree (/app/dist/frontoffice/server/main.js:81620:9)
    at destroyLView (/app/dist/frontoffice/server/main.js:81803:5)
    at RootViewRef.destroy (/app/dist/frontoffice/server/main.js:100098:7)
    at /app/dist/frontoffice/server/main.js:109238:21
    at Array.forEach (<anonymous>)
    at ApplicationRef.ngOnDestroy (/app/dist/frontoffice/server/main.js:109237:27)
```
due to missing isPlatformBrowser in line https://github.com/wynfred/ngx-masonry/blob/66534b4711c2912f2f2bafc1fe4b58070063df37/src/lib/ngx-masonry.component.ts#L154

**Comment by wynfred** [comment]
Released!
